
services:

  db:
    image: postgres:15-alpine
    container_name: blitz-postgres
    restart: always
    environment:
      POSTGRES_DB: #dbname
      POSTGRES_USER: #user
      POSTGRES_PASSWORD: #pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: blitz-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: #url
      SPRING_DATASOURCE_USERNAME: #pass
      SPRING_DATASOURCE_PASSWORD: #user

volumes:
  pgdata: