spring.application.name=tickethub

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tickethub
spring.datasource.username=postgres
spring.datasource.password=rasadnik

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000